# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit, pre-push, pre-merge-commit]
default_language_version:
    python: python3
exclude: "cython"
repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
-   repo: https://github.com/pre-commit/mirrors-isort # Using isort mirror to prevent import error
    rev: v5.10.1
    hooks:
      - id: isort # Import sorting.
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    # Find all available hooks in https://github.com/pre-commit/pre-commit-hooks/blob/main/README.md
    hooks:
    -   id: check-builtin-literals
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit # Security vulnerabilities
        args: ["--exclude", "scripts,setup.py,bin,tests,dat,cython"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy # Static type checking
        exclude: ^tests/,^dat/,^cython/
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8 # Code linting -> Focuses on PEP 8 style and basic style issues
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.2
    hooks:
    -   id: pylint # Code linting -> Deep code analysis for bugs, standards, and quality
